name: residual-rnn
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - bzip2=1.0.8
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - flake8=4.0.1
  - freetype=2.12.1
  - giflib=5.2.1
  - imageio=2.22.0
  - intel-openmp=2021.4.0
  - jpeg=9e
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libffi=3.2.1
  - libgcc-ng=11.2.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=11.2.0
  - libpng=1.6.37
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.0.3
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - lz4-c=1.9.3
  - mccabe=0.7.0
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.21.5
  - openssl=1.0.2u
  - pillow=9.2.0
  - pip=22.2.2
  - pycodestyle=2.8.0
  - pydocstyle=6.1.1
  - pyflakes=2.4.0
  - python=3.7.0
  - readline=7.0
  - setuptools=65.5.0
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sqlite=3.33.0
  - tk=8.6.12
  - typing_extensions=4.3.0
  - tzdata=2022f
  - wheel=0.37.1
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - astor==0.8.1
    - astunparse==1.6.3
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - flatbuffers==22.10.26
    - gast==0.2.2
    - google-auth==2.14.1
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.50.0
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==5.0.0
    - keras==2.10.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - libclang==14.0.6
    - markdown==3.4.1
    - markupsafe==2.1.1
    - numpy==1.21.6
    - oauthlib==3.2.2
    - opt-einsum==3.3.0
    - packaging==21.3
    - protobuf==3.19.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==3.0.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scipy==1.1.0
    - tensorboard==1.15.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow==1.15.0
    - tensorflow-estimator==1.15.1
    - tensorflow-io-gcs-filesystem==0.27.0
    - termcolor==2.1.0
    - typing-extensions==4.4.0
    - urllib3==1.26.12
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - zipp==3.10.0
